on:
  push:
    branches:
    - main
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo 'Hello World'

      - name: Terraform Init
        run: |
          terraform init
        env:
          AWS_ACCESS_KEY_ID:  ${ secrets.AWS_ACCESS_KEY_ID }
          AWS_SECRET_ACCESS_KEY:  ${ secrets.AWS_SECRET_ACCESS_KEY }
          
      - name: Terraform validate
        run: |
          terraform validate
      - name: Terraform Apply
        run: |
          terraform plan -var 'personal_access_token=${ secrets.PERSONAL_ACCESS_TOKEN }'
        env:
          AWS_ACCESS_KEY_ID:  ${ secrets.AWS_ACCESS_KEY_ID }
          AWS_SECRET_ACCESS_KEY:  ${ secrets.AWS_SECRET_ACCESS_KEY }
